# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Wtyczka_Projekt3
                                 A QGIS plugin
 Na czym polega działanie wtyczki?
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-10
        copyright            : (C) 2023 by Hubert Mizura
        email                : 01160196@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Wtyczka_Projekt3 class from file Wtyczka_Projekt3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .wtyczka_projekt import Wtyczka_Projekt3
    return Wtyczka_Projekt3(iface)
